name: Build and Distribute

on:
  push:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode_26.2.app


      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.9'

      - uses: cedvdb/action-flutter-build-ios@v1
        with:
          working-directory: skit_module
          build-cmd: flutter build ipa --release --obfuscate --split-debug-info=./symbols  --export-options-plist=ExportOptions.plist --no-tree-shake-icons    
          certificate-base64: ${{ secrets.CERTIFICATE_BASE64 }}
          certificate-password: 123
          provisioning-profile-base64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}
          keychain-password: 111111
      - name: Archive IPA
        uses: actions/upload-artifact@v4
        with:
          name: release-ipa
          path: skit_module/build/ios/archive/Runner.xcarchive
      
      - name: Upload using iTMSTransporter
        env:
          WORKING_DIRECTORY: skit_module/build/ios/ipa
          IPA_FILE_NAME: Z8VIP.ipa
          APPLE_USERNAME: alanham@landrph.top
          APPLE_PASSWORD: gwbj-yvyg-yvgp-kihy
          APPLE_ASC_PROVIDER: B36Q495V35
        run: |
          cd $WORKING_DIRECTORY
          git clone https://github.com/ZhangLi1984/itsm.git
          ./itsm/bin/iTMSTransporter -assetFile $IPA_FILE_NAME -u $APPLE_USERNAME -p $APPLE_PASSWORD -m upload -asc_provider $APPLE_ASC_PROVIDER

      - name: Clean project and update README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          git rm -rf .
          git clean -fxd
          echo "Last updated: $(date '+%Y-%m-%d %H:%M:%S')" > README.md
          git add README.md
          git commit -m "清空项目，仅保留更新时间戳的 README"
          git push origin main --force
